redditclone/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from post_app import views as post_view
from user_app import views as user_view
from comments import views as comment_view
from subreddit import views as subreddit_view


urlpatterns = [
    path('admin/', admin.site.urls),
    # Comments
    path('comment/upvote/<int:comment_id>/', comment_view.up_vote, name='comment_upvote'),
    path('comment/downvote/<int:comment_id>/', comment_view.down_vote, name='comment_downvote'),
    path('comment/edit/<int:comment_id>/', comment_view.edit_comment),
    path('comment/delete/<int:comment_id>/', comment_view.deletecomment, name='delete_comment'),
    path('comment/add/<int:post_id>/', comment_view.addcomment),
    # Posts
    path('post/<int:post_id>', post_view.PostDetailView.as_view(), name='post_detail'),
    path('addpost/', post_view.add_post),
    path('upvote/<int:post_id>/', post_view.upvote_view, name='upvote'),
    path('downvote/<int:post_id>/', post_view.downvote_view, name='downvote'),
    path('post/<int:id>/delete/', post_view.delete_view, name='post_delete'),
    path('sorted/', post_view.SortView.as_view()),
    path('post/<int:post_id>/edit/', post_view.edit_post),
    # path('upload', post_view.image_upload_view),
    # Users
    path('signup/', user_view.signup_view, name='signup'),
    path('login/', user_view.login_view, name='login'),
    path('logout/', user_view.LogOutView.as_view(), name='logout'),
    path('new/', user_view.new, name='new'),
    path('hot/', user_view.hot, name='hot'),
    path('following/', user_view.following, name="following"),
    path('', user_view.index, name='homepage'),
    # Subreddits
    path('addsubreddit/', subreddit_view.add_subreddit, name='addsubreddit'),
    path('r/<str:name>/', subreddit_view.subredditview, name='subreddit'),
    path('r/<str:name>/new/', subreddit_view.subredditnew, name='subredditnew'),
    path('r/<str:name>/hot/', subreddit_view.subreddithot, name='subreddithot'),
    path('subscribed/<int:id>/', subreddit_view.subscribe, name='subscribe'),
    path('unsubscribed/<int:id>/', subreddit_view.unsubscribe, name='unsubscribe'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post_app/models.py
from django.db import models
from user_app.models import RedditUser
from subreddit.models import SubReddit
from django.utils import timezone


class CommonFieldsMixin(models.Model):
    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)
    author = models.ForeignKey(RedditUser, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    votes = models.IntegerField(default=0)

    def votes(self):
        return self.upvotes - self.downvotes

    class Meta:
        abstract = True

class Post(CommonFieldsMixin, models.Model):
    ''' 
        Special information for the Posts
    '''
    TYPE_POST = (('Text', 'Text'), ('Link', 'Link'), ('Image', 'Image'))

    type_post = models.CharField(max_length=7, choices=TYPE_POST, default='Text')
    title = models.CharField(max_length=150)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    url_post = models.URLField(blank=True, null=True)
    subreddit = models.ForeignKey(SubReddit, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title


# class Image(models.Model):
#     title = models.CharField(max_length=200)
#     image = 

templates/add_post.html
{% load static %}
<!-- {% static 'static_jquery/js/jquery.js' %} -->
<html>
<head>
  <title>Reddit</title>
  <link rel="icon" href="https://cdn.worldvectorlogo.com/logos/reddit-2.svg" type="image/x-icon">

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <title>Reddit</title>
  <link rel="icon" href="https://cdn.worldvectorlogo.com/logos/reddit-2.svg" type="image/x-icon">
</head>

<body style='margin-left: 50px;'>
  {% include 'header_content.html' %}
  <div class="form-group">
    <form method="POST" enctype="multipart/form-data"></form>
  </div>
  <div>
    <form class='form' method="post" action="" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="row">
      <div class="col-3"></div>
      <div class="card col-6">

      <div class='field col-4'>
        <label class="label" for="{{ field.auto_id }}">{{ form.title.label }}:</label>
        {{ form.title }} 
      </div>
      
      <div class='field col-4'>
        <label class="label" for="{{ field.auto_id }}">{{ form.type_post.label }}:</label>
        {{ form.type_post }} 
      </div>
      
      <div class='field col-4' id='Text'>
        <label class="label" for="{{ field.auto_id }}">{{ form.content.label }}:</label>
        {{ form.content }} 
      </div>   
      <div class='field col-4' id='Link'>
        <label class="label" for="{{ field.auto_id }}">{{ form.url_post.label }}:</label>
        {{ form.url_post }} 
      </div>   
      <div class='field col-4' id='Image'>
        <label class="label" for="{{ field.auto_id }}">{{ form.content.label }}:</label>
        {{ form.image }} 
      </div>
     
      <div class='field col-4' id='subreddit'>
        <label class="label" for="{{ field.auto_id }}">{{ form.subreddit.label }}:</label>
        {{ form.subreddit }} 
      </div>
      <input type="submit" value="Submit" class='button submit-bttn'/>
      </div>
      </div>
    </form>
    </div>
    <script type='text/javascript' src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script> 
      // wait for the DOM to be loaded 
      $(document).ready(function() { 
        $('#Text').show();
        $('#Link').hide();
        $('#Image').hide();
      }); 
    </script> 
    <script type='text/javascript'>
    // Credit to Stack Overflow snackerfish on implementing Jquery
      $('#id_type_post').on('change', function (e) {
        var optionSelected = $("option:selected", this);
        var valueSelected = this.value;
        console.log(optionSelected)
        if (valueSelected === 'Text'){
            $('#Text').show();
            $('#Link').hide();
            $('#Image').hide();
        } else if (valueSelected === 'Link') {
            $('#Text').hide();
            $('#Link').show();
            $('#Image').hide();
        } else if (valueSelected === 'Image') {
            $('#Text').hide();
            $('#Link').hide();
            $('#Image').show();
        }
    });
    </script>
  </body>
</html>

templates/display_images.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
</script>


{% for image in images %}

{{ image.name }}

<img src="{{ image.hotel_Main_img.url}}" class="img-responsive" style="width: 20%; height: 20%; float: left; margin-right: 10px;" />
</div>
{% endfor %}

templates/generic_form.html
{% load static %}
<html>
<head>
  <title>Reddit</title>
  <link rel="icon" href="https://cdn.worldvectorlogo.com/logos/reddit-2.svg" type="image/x-icon">

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <title>Reddit</title>
  <link rel="icon" href="https://cdn.worldvectorlogo.com/logos/reddit-2.svg" type="image/x-icon">
</head>
  
<body style='margin-left: 50px;'>
  {% include 'header_content.html' %}
  <div class="row">
    <div class="col-3"></div>
      <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
      </form>
    </div>
</body>
</html>

templates/header_content.html
<h1 style="text-align: center;">Reddit-Clone</h1> 
<nav class='row' >
    <div class="col-sm-9">
        <a href='/' class='navbar-item'>Home</a>
    </div>
    
    <div class="col-sm-3">
        <div class='field is-grouped'>
            {% if user.is_authenticated %}
            <span>{{ request.user.username }} | </span>
            <a href='/logout/'><button class='button is-danger'>Logout</button></a>
            {% else %}
            <a href='/signup/' class="add-right"><button class='button is-danger'>Sign Up</button></a>
            <a href='/login/'><button class='button is-black'>Login</button></a>
            {% endif %}
        </div>
    </div>
</nav>
<hr>

templates/images.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Images</title>
</head>
<body>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Upload</button>
  </form>
</body>
</html>

templates/index.html
<h1>All Posts</h1>

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
{% for image in images %}

{{ image.name }}

<img src="{{ image.hotel_Main_img.url}}" class="img-responsive" style="width: 100%; float: left; margin-right: 10px;" />
</div>
{% endfor %}


<button style="margin-right: 5px;"><a href="/addpost">Add New Post</a></button>
<button><a href="/sorted">Sort by Vote Score</a></button>

{% if posts %}
    {% for post in posts %}
        <h2>Post Title: <a href="/post/{{post.id}}">{{post.title}}</a></h2>
        {{post.title}}
        <br />
        Post URL: {{post.url_post}}
        <br />
        Post Content: {{post.content}}
        <br />
        Vote Score: {{post.votes}}
        <br />
        <button><a href="/post/{{post.id}}/edit">Edit Post</a></button>
        <button><a href="/upvote/{{post.id}}/">Up Vote</a></button>
        <button><a href="/downvote/{{post.id}}/">Down Vote</a></button>
        Created at: {{post.created_at}}
        <br />
        <button style="margin-top: 10px;"><a href="/post/{{post.id}}/delete">Delete Post</a></button>
    {% endfor %}
{% endif %}
    <h1> This is the index and the view is working </h1>

    <div class="navbar-end">
        <div class='navbar-item'>
            <div class='field is-grouped'>
                {% if user.is_authenticated %}
                <a href="/user/{{ user.username }}" class='navbar-item add-right' id='usr-color'>{{ request.user.username }}</a>
                <button class='button is-danger'><a href='/logout/'>Logout</a></button>
                <a href='/user/{{ user.username }}' class='navbar-item' id='profile'>Profile</a>
                {% else %}
                <button class='button is-danger'><a href='/signup/' class="add-right">Sign Up</a></button>
                <button class='button is-black'><a href='/login/'>Login</a></button>
                <a class='navbar-item' id='profile' disabled>Profile</a>
                {% endif %}
            </div>
        </div>
    </div>

templates/login.html
<!-- <form action='' method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Please Login!">
</form>
<a href='/signup'><button>SignUp</button></a> -->


<!doctype html>
<html lang="en">

<head>
 
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <title>Login</title>
  <link rel="icon" href="https://cdn.worldvectorlogo.com/logos/reddit-2.svg" type="image/x-icon">
</head>


<h1 style="text-align: center;margin-top: 25vh;">Login</h1>
<div class="row">
  <div class="col-4"></div>
  <div class="col-4">
    <form method="post">
      {% csrf_token %}
      {{form.as_p}}
        <input style="margin-top: 5px; text-align:center" type="submit" class="btn btn-primary" value="Login">
    </form>
    <a href="/"><button class="btn btn-primary" style="margin-top: 5px; text-align:center">Home</button></a>
    <p>Don't have an account?<a href="{% url 'signup'%}"> Signup here...</a></p>
  </div>
</div>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
  integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
  integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
  integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>

</html>

templates/main.html
<html>
<head>
    <title>Reddit</title>
    <link rel="icon" href="https://cdn.worldvectorlogo.com/logos/reddit-2.svg" type="image/x-icon">

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>Reddit</title>
    <link rel="icon" href="https://cdn.worldvectorlogo.com/logos/reddit-2.svg" type="image/x-icon">
</head>
<body style='margin-left: 50px;'>
{% include 'header_content.html' %}
<div >
    {% if request.path == '/' %}
    <div class="btn-group btn-group-toggle" data-toggle="buttons">
        <label class="btn btn-secondary active"> <input type="radio" name="options" id="option1" checked> All </label>
        <label class="btn btn-secondary"> <input type="radio" name="options" id="option2"
            onclick="location.href='/hot/'">
            Hot </label>
            <label class="btn btn-secondary"> <input type="radio" name="options" id="option3"
                onclick="location.href='/new/'">
            New </label>
        </div>
        
        
        {% elif request.path == '/hot/' %}
    <div class="btn-group btn-group-toggle" data-toggle="buttons">
        <label class="btn btn-secondary"> <input type="radio" name="options" id="option1" onclick="location.href='/'">
            All
        </label>
        <label class="btn btn-secondary active"> <input type="radio" name="options" id="option2" checked> Hot </label>
        <label class="btn btn-secondary"> <input type="radio" name="options" id="option3"
                onclick="location.href='/new/'">
                New </label>
            </div>
            
    {% elif request.path == '/new/' %}
    <div class="btn-group btn-group-toggle" data-toggle="buttons">
        <label class="btn btn-secondary"> <input type="radio" name="options" id="option1" onclick="location.href='/'">
            All
        </label>
        <label class="btn btn-secondary"> <input type="radio" name="options" id="option2"
                onclick="location.href='/hot/'">
                Hot </label>
                <label class="btn btn-secondary active"> <input type="radio" name="options" id="option3" checked> New </label>
            </div>
    {% endif %}
</div>
</p>



<div class="add">
    <button onclick="location.href='/addpost'" style="margin-left: 900px;">Add Post</button>
</div>
<div class="row">
    <div class="col-8" style="margin-left:40px;">
        {% include 'posts.html' %}
    </div>
    <div class="col-3">
        {% if user.is_authenticated %}
        <a href="/addsubreddit/" style="text-decoration:none;color:white;"><button type="button" class="btn btn-success"
                style="width:100%; margin-bottom:10px">Create Community</button></a>
                {%endif%}
                <div class="card">
                    <h4 style="text-align:center;margin-top:10px;margin-bottom:0px;">Subreddits ({{sub_r_count}})</h4>
                    <hr>

                    {% for subreddit in subreddits %}
                    {% if request.user.is_authenticated %}
                    {% if subreddit not in subscribe_list %}
                    <p style="margin:10px;"><a href="/r/{{subreddit.name}}/">/r/{{subreddit}}</a> <a
                            href="/subscribed/{{subreddit.id}}/" style="text-decoration: none; color: rgb(64, 185, 64)">Join</a></p>
                            {% else %}
                            <p style="margin:10px;"><a href="/r/{{subreddit.name}}/">/r/{{subreddit}}</a> <a
                            href="/unsubscribed/{{subreddit.id}}/" style="text-decoration: none; color: rgb(64, 185, 64)">Unjoin</a></p>
                            {% endif %}
                            {% else %}
                    <p style="margin:10px;"><a href="/r/{{subreddit.name}}/">/r/{{subreddit}}</a> <a
                        href="/login?next={{ request.path }}" style="text-decoration: none; color: rgb(64, 185, 64)">Join</a></p>
                        {% endif %}
                        {% endfor %}
                    </div>
                    <p></p>
    </div>
</div>
</body>
</html>

templates/post.html
<!doctype html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

 
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  <title>Reddit</title>
  <link rel="icon" href="https://cdn.worldvectorlogo.com/logos/reddit-2.svg" type="image/x-icon">
</head>


<div class="row">
  <div class="col-sm-3" align="center"><a href="/">Home</a> |
    <a href="/r/{{post.subreddit.name}}/">Back to Subreddit</a>
  </div>
  <div class="col-sm-6"></div>
  <div class="col-sm-3">
    {% if user.is_authenticated %}
    Logged in as : {{user}}
    <a href="/logout?next={{ request.path }}">
      Logout</a> <br />
    {%else%}
    <a href="/login?next={{ request.path }}">Login</a> |
    <a href="/signup?next={{request.path}}"> Sign up </a>
    {%endif%}
  </div>
</div>

<hr style="margin:0;">
<div class="row" style="text-align:center">
  <div class="col-1"></div>
  <div class="col-lg-10" style="height:20vh;margin:0;width:100vw;">
    <h1 style="font-size:100px;">{{post.subreddit.name}}</h1>
  </div>
  <div class="col-1"></div>
</div>
<hr>

<div class="row">
  <div class="col-2"></div>
  <div class="card col-8">
    <p></p>
    <div class="card">
      <div class="col-7">
        <h2>{{post.title}}</h2>
        <p>{{post.body}}</p>
        <p>{{post.date_created}}
          
          <span>
            {%if user%}
            <button><a href="/upvote/{{post.id}}?next={{ request.path }}"
                style="text-decoration:none; color:green">⇧</a></button>
            {{post.score}}
            <button><a href="/downvote/{{post.id}}?next={{ request.path }}"
                style="text-decoration:none; color:red">⇩</a></button>
            {% else %}
            <button><a href="/login?next={{ request.path }}" style="text-decoration:none; color:green">⇧</a></button>
            {{post.score}}
            <button><a href="/login?next={{ request.path }}" style="text-decoration:none; color:red">⇩</a></button>
            {%endif%}
          </span></p>

        {%if user.is_authenticated%}
        {% include 'templates/comments/addcomment.html' %}
        {%endif%}
      </div>
    </div>

    <p>
    <div class="col-2"></div>
    <div class="col-11">
      {% include 'templates/comments/comments.html' %}
    </div>
  </div>
  
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
    crossorigin="anonymous"></script>
  </body>

</html>

templates/post_detail.html
<html>
<head>
  <title>Reddit</title>
  <link rel="icon" href="https://cdn.worldvectorlogo.com/logos/reddit-2.svg" type="image/x-icon">

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <title>Reddit</title>
  <link rel="icon" href="https://cdn.worldvectorlogo.com/logos/reddit-2.svg" type="image/x-icon">
</head>


<body style='margin-left: 50px;'>
    {% include 'header_content.html' %}
    <button style="margin-bottom: 15px;"><a href="/addpost">Add Post</a></button>
    <button style="margin-right: 5px;"><a href="/post/{{post.id}}/edit">Edit Post</a></button>
    <button style="margin-top: 10px;"><a href="/post/{{post.id}}/delete">Delete Post</a></button>
    
    <br />
    
    
    <h1>Post Content</h1>
    
    Title: {{post.title}}
    <br />
    <!-- Url: {{post.url_post}} -->
Post Content: {{post.content}}
</br>
Created at: {{post.created_at}}
<br />
<br />
{% if post.image %}<img src="{{post.image.url}}" alt="post image" height="80px" width="80px">{% endif %}
<h4>Comments:</h4>
{% for comment in comments %}
<div class="comment">
  <p class="info">
  </p>
  {{ comment.body }}
  <br />
  {{comment.created_at}}
  <br />
  Comment Score: {{comment.votes}}
  
  <a href="/comment/upvote/{{comment.id}}?next={{ request.path }}"><button style="text-decoration:none; color:green">⇧</button></a>
    <a href="/comment/downvote/{{comment.id}}?next={{ request.path }}"><button style="text-decoration:none; color:red">⇩</button></a>
    </div>
    <a href="/comment/edit/{{comment.id}}"><button style="margin-right: 5px;">Edit Comment</button></a>
    <a href="/comment/delete/{{comment.id}}"></a><button style="margin-top: 10px;">Delete Comment</button></a>
    
    
    <br />
    {% endfor %}
    <br />
    <h4>Add Comment</h4>
    {% include 'comments/addcomment.html'%}
    <br />

  </body>
</html>
  
  

templates/posts.html
{% for post in posts %}
<div class="card">

  <div class="card-body">
    <h3>
      <ul>
        <li style="list-style-type: none;">
          <a href="/post/{{post.id}}">{{ post.title }}</a>
        </li>
      </ul>
    </h3>
    <ul>


      <span>
        {% if user.is_authenticated %}
        <button><a href="/upvote/{{post.id}}?next={{ request.path }}"
            style="text-decoration:none; color:green">⇧</a></button>
        {{post.votes}}
        <button><a href="/downvote/{{post.id}}?next={{ request.path }}"
            style="text-decoration:none; color:red">⇩</a></button>
       
        {% if post.author == request.user or request.user in moderators %}
        <button><a href="/post/{{post.id}}/delete/" style="text-decoration: none; color: red">Delete</a></button>
        {% endif %}
       
        {% else %}
        <button><a href="/upvotes/{{post.id}}?next={{ request.path }}" style="text-decoration:none; color:green">⇧</a></button>
        {{post.votes}}
        <button><a href="/login?next={{ request.path }}" style="text-decoration:none; color:red">⇩</a></button>
        {%endif%}
      </span>
      Submitted on {{post.created_at}} by {{post.author}} from <a
        href="/r/{{post.subreddit}}">r/{{ post.subreddit }}</a>
    </ul>
  </div>
</div>
<p>
{% endfor %}

templates/signup.html
<!-- <form action='' method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Sign Up Here!">
</form>
<button class='button is-black'><a href='/login/'>Login</a></button> -->

<!doctype html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <title>Signup</title>
  <link rel="icon" href="https://cdn.worldvectorlogo.com/logos/reddit-2.svg" type="image/x-icon">
</head>


<h1 style="text-align: center;margin-top: 25vh;">Signup</h1>
<div class="row">
  <div class="col-4"></div>
  <div class="col-4">
    <form method="post">
      {% csrf_token %}
      {{form}}
      {% if messages %}
      <ul class="messages">
        {% for message in messages %}
        <span style="color:red">
          {{ message }}
        </span>

        {% endfor %}
      </ul>
      {% endif %}
        <input style="margin-top: 5px; text-align:center" type="submit" class="btn btn-primary" value="Signup here...">
    </form>
    <a href="/"><button class="btn btn-primary" style="margin-top: 5px; text-align:center">Home</button></a>
  </div>
</div>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
  integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
  integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
  integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>

</html>